### PR TITLE
Parallelism and error handling

### PR DESCRIPTION
**Pull request by ZenTauro**
I've added parallelism when updating and building the templates, error handling using the logger and some internal documentation.

Also a bump in version and the `.vscode` directory in the `.gitignore`

### CODE REVIEW

**Comment by ilpianista** [comment]
Parallelism is something I would like to implement since day 1, thank you a lot for taking a look at this!
However, I don't want to require nightly. Is there any way you rework it to avoid nightly?

Also, `builder update` is the only command this tool should provide. Any other would not make it [complaint](http://chriskempson.com/projects/base16/?#builder-guidelines).

Meantime, please open a new PR with just doc and minor fixes if possible.

**Comment by ZenTauro** [comment]
You're welcome! I've reverted those changes and the need to use nightly

**Comment by ilpianista** [comment]
Hi, thanks, but I cannot merge this as it is. Can you please rebase it to remove the reverted commits and split changes (one commit for additional docs, one commit for parallelism etc...)?

**Comment by ZenTauro** [comment]
Sure, I'll open a different pr with those changes as soon as I make them.

**Pull request closed without merging**
